# Generated by Django 3.0.5 on 2020-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
